{% set name = "asdf" %}
{% set version = "2.7.3" %}
{% set sha256 = "f7ea14e4df23ec5d94a9c1f2ed743526f7c4df3c9253ebd915b5585e92c8be85" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  entry_points:
    - asdftool = asdf.commands.main:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - setuptools_scm
  run:
    - python >=3.6
    - pyyaml >=3.10
    - jsonschema >=2.3.0
    - pytest >=2.7.2
    - numpy >=1.8
    - semantic_version >=2.8

test:
  imports:
    - asdf
    - asdf.commands
    - asdf.extern
    - asdf.tags
    - asdf.tags.core
  commands:
    - asdftool --help

about:
  home: http://github.com/spacetelescope/asdf
  license: BSD-3-Clause
  license_family: BSD
  license_file: licenses/LICENSE.rst
  summary: Python tools to handle ASDF files
  description: |
    Python library for reading and writing ASDF files. The Advanced Scientific
    Data Format (ASDF) is a next generation interchange format for scientific
    data.
  doc_url: http://asdf.readthedocs.io/
  dev_url: http://github.com/spacetelescope/asdf
